### ISSUE TITLE
[Enhancement] Treat all require as promises

### ISSUE THREAD

**Issue by jbblanchet** [jokeyrhyme/requirejs-promise#6]
Hi,

It's nice to be able to load promises-returning dependencies, but it'd be even nicer to be able to load any dependencies and treat it as a promise, so when I need to manually a js module, even a non promise returning one, I can simply work with a promise. Something like:

``` javascript
reqpromise("foo/bar").then(function (result) {
   // fantastic code!
}, function (error) {
   // oups
});
```

Is this something you see as part of your library? I'm willing and (mostly) able to help.

**Comment by jokeyrhyme** [comment]
Using native Promises (or Bluebird, etc), you could define this as something like:

``` javascript
function reqpromise (id) {
  return new Promise(function (resolve, reject) {
    require([id], function (result) {
      resolve(result);
    }, function (err) {
      reject(err);
    });
  });
};
```

Promises are great for waiting for multiple asynchronous tasks to complete, or putting them in a fixed sequence. AMD, on the other hand, does much the same thing except the asynchronous tasks are always the loading of a JavaScript module(s).

I can see a use case for the suggested functionality: mix and match asynchronous tasks and the loading of modules. Does this happen a fair bit in the projects you have in mind? Or is this mostly about converting a callback-style interface into a Promise interface?

**Comment by jbblanchet** [comment]
This is mostly an exercise of seeing how far I can go with promises, but I'll give you an example of a scenario I have in mind. Let's say you have a SPA that contains a dashboard with widgets. To render a widget, you might need a combination of:
- A view (knockout, handlebar, whatever).
- A model, viewmodel, controller, module (i.e. some js).
- A css file.
- Some data, maybe from more than 1 source, either via an API call, a CSV, etc.
- Maybe a svg file (because why not?).

Let's say I want to build an engine to render this. There's plenty of tools to do this, but each has it's own type of callback or half-promises (I'm looking at you jQuery). It would be much easier if everything was returning a promise instead of having it's own callback.

Not surprisingly, I found your repository while looking for "requirejs promises". Since you're already doing something similar, I was merely checking in to see if it was in the plans or not.

**Comment by jokeyrhyme** [comment]
Most of those separate pieces should be declaring AMD modules and dependencies, especially if you're in a project that uses Require.JS.

The data source is the only thing that might need to be downloaded multiple times / refreshed, so you shouldn't use AMD for that. And I'd actually suggest that an event system would make more sense for the data sources (rather than Promises), so that the rest of your widget more easily updates whenever there's new data.

I guess what you're proposing is that this ...

``` javascript
Promise.all([
  reqpromise('a'), reqpromise('b'), reqpromise('c'), reqpromise('d'), getCSS('e'), insertSVG('f')
]).then(function (a, b, c, d) {
  // TODO: ...
});
```

... looks better than this ...

``` javascript
require([
  'a', 'b', 'c', 'd'
], function (a, b, c, d) {
  Promise.all([ getCSS('e'), insertSVG('f') ]).then(function () {
    // TODO: ...
  });
});
```

It's a tough call. This project is a fairly focused Require.JS plugin. I just don't see a compelling reason to incorporate a Promise wrapper at this stage. However, if you start a separate project for the component we've discussed here, I'd gladly link to it from my README.

**Comment by jbblanchet** [comment]
Sorry for the delay, I fried my computer this weekend.

It's not simply a question of style. A large motivation for me is simply the encapsulating power of promises. If everything uses promises, then everything is pluggable. I don't have to care about what my dependencies are, or what I use to fetch them. Each one is a promise for something, and I can concentrate on manipulating promises and managing their result (including any exception thrown).

I'll close the issue for now. I had hoped to have something to show you today, but my computer had other plans. But if you're interested I'll come back and keep you posted when I have something more tangible, probably later this week.

**Comment by jokeyrhyme** [comment]
Do post updates. Please.

I'm also curious to see what @jrburke thinks of this subject. Exposing a Promise interface to AMD is something that might be useful to consider for Require.JS proper.

**Comment by jrburke** [comment]
The only promise capability exposed I expect may be from a require([]) call, but I also do not expect to see any real progress on that until interop with ES6 loaders is better defined. The plus side is that an ES6 loader will seem to use promises for its equivalent API.

**Comment by jokeyrhyme** [comment]
@jrburke would it make sense for me or @jbblanchet to lodge an Issue over in the upstream Require.JS project about this? Pending the ES6 Modules specification, is this something that you'd be open to including in Require.JS?

**Comment by jrburke** [comment]
It is not far enough along for me to consider it yet, so I don't want the ticket languishing. It will likely just fall out of any ES6 interop though.

**Comment by jokeyrhyme** [comment]
@jrburke cool beans. Just one more question, is it possible / likely that the Promise-unwrapping behaviour of this plugin project will become part of upstream Require.JS too, as part of this ES6 interoperability?

**Comment by jrburke** [comment]
Whatever native promises + es6 exporting does is likely what I will match in requirejs.

**Comment by jbblanchet** [comment]
@jokeyrhyme Here's what I had in mind. It's not much, but I think the basic structure is there.

https://github.com/jbblanchet/qurandal

**Comment by jokeyrhyme** [comment]
My advice would be to maintain your Promise-based wrapper around the AMD APIs as necessary in your own code (or in a separate component project) for now. As discussed here, it's possible that Require.JS itself will swallow up both your idea and the functionality of my plugin as part of compatibility with ES6 Modules.
