### ISSUE TITLE
Path resolution issues with the simplified define wrapper

### ISSUE THREAD

**Issue by gotomanners** [jokeyrhyme/requirejs-promise#8]
I'm getting path resolution errors with the setup below.

requireconfig.js

```
require.config({
    config: {
        paths: {
            'promise': 'app/js/libs/requirejs-promise'
            'myNamedAsyncModule': 'promise!app/js/myAsyncModule'
        }
    }
});
```

In app.js

```
define(function (require) {
    var asyncModule = require('myNamedAsyncModule');
    // TODO: do something cool with asyncModule
});
```

It tries to resolve the asyncModule with a path as such
`http://localhost/project/script/promise!/app/js/myAsyncModule.js`

Is it not possible to configure an asyncModule path in require.config?

**Comment by jokeyrhyme** [comment]
http://requirejs.org/docs/api.html#plugins

I've never seen mixing plugins and paths work. As far as I'm aware, plugins are only supported in the call to `define()` or `require()`. I believe paths are expected to be URLs (or "empty:" to prevent loading).

**Comment by jokeyrhyme** [comment]
Please reopen this if you find another Require.js plugin that works in the `paths` section like this. At this point I think this is more of a question for upstream than it is a problem specifically with this plugin. Cheers.
